### PR TITLE
fix typo. "you're finished" twice

### PR DESCRIPTION
**Pull request by harry-wood**

### CODE REVIEW

**Comment by harry-wood** [comment]
I saw the typo on tryruby.org here: http://tryruby.org/levels/1/challenges/1   but where's the right place to fix typos on that site?

**Comment by jnv** [comment]
Thanks Harry! This is an independent project developed by one of our students. AFAIK tryruby.org sadly isn't open-source, you probably need to contact Code School.

**Comment by jnv** [comment]
@deric Could you push v0.0.3 to Rubygems please?

**Comment by deric** [comment]
@jnv released

**Pull request merged**
